# Generated by Django 4.2.2 on 2023-06-28 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("type", "0003_alter_stats_wpm_a_alter_stats_wpm_b_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stats",
            name="accuracy",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="stats",
            name="mode",
            field=models.CharField(default="", max_length=20),
        ),
    ]
