# Generated by Django 4.2.2 on 2023-06-28 00:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("type", "0004_stats_accuracy_stats_mode"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Stats",
            new_name="Stat",
        ),
    ]
