# Generated by Django 4.2.2 on 2023-07-10 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("type", "0007_stat_chars"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stat",
            name="chars",
        ),
    ]
